export const INSPECTOR_ATTRIBUTE = "inspector";
export const INSPECTOR_NAME_ATTRIBUTE = "inspector-name";
export const INSPECTOR_ATTRIBUTE_DATA_KEY = `data-${INSPECTOR_ATTRIBUTE}`;
export const INSPECTOR_NAME_ATTRIBUTE_DATA_KEY = `data-${INSPECTOR_NAME_ATTRIBUTE}`;
export const INSPECTOR_IGNORE_ATTRIBUTE = "inspector-ignore";
export const INSPECTOR_IGNORE_ATTRIBUTE_DATA_KEY = `data-${INSPECTOR_IGNORE_ATTRIBUTE}`;
