/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChar123SessionIdChar125RouteImport } from './routes/chat.{-$sessionId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChar123SessionIdChar125Route =
  ChatChar123SessionIdChar125RouteImport.update({
    id: '/chat/{-$sessionId}',
    path: '/chat/{-$sessionId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/{-$sessionId}': typeof ChatChar123SessionIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/{-$sessionId}': typeof ChatChar123SessionIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/{-$sessionId}': typeof ChatChar123SessionIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/{-$sessionId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/{-$sessionId}'
  id: '__root__' | '/' | '/chat/{-$sessionId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatChar123SessionIdChar125Route: typeof ChatChar123SessionIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/{-$sessionId}': {
      id: '/chat/{-$sessionId}'
      path: '/chat/{-$sessionId}'
      fullPath: '/chat/{-$sessionId}'
      preLoaderRoute: typeof ChatChar123SessionIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/chat.{-$sessionId}' {
  const createFileRoute: CreateFileRoute<
    '/chat/{-$sessionId}',
    FileRoutesByPath['/chat/{-$sessionId}']['parentRoute'],
    FileRoutesByPath['/chat/{-$sessionId}']['id'],
    FileRoutesByPath['/chat/{-$sessionId}']['path'],
    FileRoutesByPath['/chat/{-$sessionId}']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatChar123SessionIdChar125Route: ChatChar123SessionIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
